In [1]:
import numpy as np

In [3]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
b = np.array([i for i in range(10)], dtype=np.float32)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
b.dtype

dtype('float64')

In [14]:
print(b.ndim)
print(b.shape)

1
(10,)


In [16]:
c = np.array([
    [i for i in range(10)],
    [i for i in range(10, 20)],
    [i for i in range(20, 30)]
])
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [19]:
print(c.ndim)
print(c.shape)

2
(3, 10)


In [25]:
print(c[1][1])
print(c[1, 1])
print(c[1:, :3])

11
11
[[10 11 12]
 [20 21 22]]


In [30]:
c[1:, :3].copy()

array([[10, 11, 12],
       [20, 21, 22]])

In [32]:
a = np.array(range(5))
b = np.array(range(5, 10))
print(a)
print(b)

[0 1 2 3 4]
[5 6 7 8 9]


In [36]:
print(a + b)
print(np.add(a, b))

[ 5  7  9 11 13]
[ 5  7  9 11 13]


In [37]:
print(a * 2)
print(np.dot(a, 2))
print(a.dot(2))

[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]


In [39]:
print(np.dot(a, b))# скалярное произведение
print(a.dot(b))

80
80


In [43]:
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

B = np.array([
    [6, 7],
    [8, 9],
    [10, 11]
])

print(A + B)
print(np.add(A, B))

[[ 6  8]
 [10 12]
 [14 16]]
[[ 6  8]
 [10 12]
 [14 16]]


In [44]:
X1 = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

X2 = np.array([
    [6, 7, 8],
    [9, 10, 11]
])

print(X1)
print(X2)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [50]:
C = np.dot(X1, X2)
print(np.dot(X1, X2))
print(X1.dot(X2))

[[ 9 10 11]
 [39 44 49]
 [69 78 87]]
[[ 9 10 11]
 [39 44 49]
 [69 78 87]]


In [52]:
print(np.dot(C, C))
print(np.linalg.matrix_power(C, 2))

[[ 1230  1388  1546]
 [ 5448  6148  6848]
 [ 9666 10908 12150]]
[[ 1230  1388  1546]
 [ 5448  6148  6848]
 [ 9666 10908 12150]]


In [53]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
print(A.transpose())
print(A.T)

[[0 2 4]
 [1 3 5]]
[[0 2 4]
 [1 3 5]]


In [57]:
X = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

Y = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7]
])

print(X.dot(Y.T))

[[ 1  3  5  7]
 [ 3 13 23 33]
 [ 5 23 41 59]]


In [59]:
print(np.linalg.det(C))
print(np.linalg.matrix_rank(C))

3.455207134898618e-14
2


In [60]:
print(np.linalg.inv(C))

[[ 1.73650950e+14 -3.47301899e+14  1.73650950e+14]
 [-3.47301899e+14  6.94603798e+14 -3.47301899e+14]
 [ 1.73650950e+14 -3.47301899e+14  1.73650950e+14]]


In [64]:
print(np.zeros((3, 4)))
print(np.ones((2, 5)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
print(np.arange(0, 10, 2))
print(np.linspace(1, 9, 10))
print(np.logspace(0, 3, 4))

[0 2 4 6 8]
[1.         1.08080808 1.16161616 1.24242424 1.32323232 1.4040404
 1.48484848 1.56565657 1.64646465 1.72727273 1.80808081 1.88888889
 1.96969697 2.05050505 2.13131313 2.21212121 2.29292929 2.37373737
 2.45454545 2.53535354 2.61616162 2.6969697  2.77777778 2.85858586
 2.93939394 3.02020202 3.1010101  3.18181818 3.26262626 3.34343434
 3.42424242 3.50505051 3.58585859 3.66666667 3.74747475 3.82828283
 3.90909091 3.98989899 4.07070707 4.15151515 4.23232323 4.31313131
 4.39393939 4.47474747 4.55555556 4.63636364 4.71717172 4.7979798
 4.87878788 4.95959596 5.04040404 5.12121212 5.2020202  5.28282828
 5.36363636 5.44444444 5.52525253 5.60606061 5.68686869 5.76767677
 5.84848485 5.92929293 6.01010101 6.09090909 6.17171717 6.25252525
 6.33333333 6.41414141 6.49494949 6.57575758 6.65656566 6.73737374
 6.81818182 6.8989899  6.97979798 7.06060606 7.14141414 7.22222222
 7.3030303  7.38383838 7.46464646 7.54545455 7.62626263 7.70707071
 7.78787879 7.86868687 7.94949495 8.03030303 8.11111

In [73]:
print(np.random.sample((2, 3)))# равномерное распределение [0, 1)
print(np.random.randn(3, 4))# нормальное распределение со средним отклонением 1
print(np.random.randint(0, 10, (3, 4)))

[[0.36987394 0.93750502 0.76891304]
 [0.41214497 0.00661604 0.77383032]]
[[ 0.01817144 -0.92172687  0.35355228 -1.24540368]
 [ 0.18872858 -1.03833523  0.11517006  1.75616314]
 [-0.75068119 -0.10077845  0.30344126 -0.05557916]]
[[4 2 0 6]
 [6 8 1 1]
 [6 2 5 5]]


In [76]:
b = np.array([0, 1, 2, 3])
print(np.random.choice(b, 2))

[1 3]


In [81]:
np.random.seed(42)
np.random.randint(0, 10, 10)

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

In [93]:
a = np.array([0, 1, 2, 3])
print(a.reshape(-1, 2))
a.resize(2, 2)
print(a)
print(a.flatten())

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[0 1 2 3]


In [98]:
a = np.zeros((2, 4))
b = np.ones((2, 4))
print(np.vstack((a, b)))
print(np.concatenate((a, b), axis=0))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [99]:
print(np.dstack((a, b)))

[[[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]]


In [100]:
a = np.random.randint(0, 20, 10)
a

array([ 3,  7,  2,  1, 11,  5,  1,  0, 11, 11])

In [105]:
a[(a < 10) & (a % 2 == 0)]

array([2, 0])

In [107]:
a[np.where(a < 10)]

array([3, 7, 2, 1, 5, 1, 0])

In [109]:
a = [1, 3, 5, 7]
b = [2, 4, 6, 8]
np.where([True, True, False, False], a, b)

array([1, 3, 6, 8])

In [113]:
a = np.array([[1, 3, 9, 9],
              [5, 0, 1, 5],
              [2, 7, 3, 5]])

print(a[[0, 2, 1], :])# срез по индексам строк и всем колонкам

print(a.argsort(axis=0))# индексы строк при сортировке по столбцу
a[:, 0].argsort(axis=0)# индексы строк при сортировке среза по первому столбцу
print(a[a[:, 0].argsort(axis=0), :])

[[1 3 9 9]
 [2 7 3 5]
 [5 0 1 5]]
[[0 1 1 1]
 [2 0 2 2]
 [1 2 0 0]]
[[1 3 9 9]
 [2 7 3 5]
 [5 0 1 5]]


In [117]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 5 6 4 3 1 7 2 0 8]


In [123]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.log(a))
print(np.exp(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [127]:
print(a.sum(axis=0))# сумма
print(a.min(axis=0))# минимальное
print(a.mean(axis=0))# средневзвешаннное
print(a.std(axis=0))# среднеквадратичное отклонение

[5 7 9]
[1 2 3]
[2.5 3.5 4.5]
[1.5 1.5 1.5]
